---
title: "Prepare OmnipathR datasets for offline use"
author: "RA ([numpde](https://github.com/numpde/))"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output: 
  html_document:
    toc: true
    toc_depth: 2
editor_options:
 chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(out.width = "100%")
```

OmnipathR:
[Vignette](https://saezlab.github.io/OmnipathR/articles/OmnipathMainVignette.html).

## Preliminaries {.tabset .tabset-fade}

### Setup

```{r}
suppressPackageStartupMessages({
  # install.packages("kableExtra")
  requireNamespace("kableExtra")

  # install.packages("dplyr")
  library(dplyr)

  # BiocManager::install("OmnipathR")
  requireNamespace("OmnipathR")

  requireNamespace("readr")
})
```

### SessionInfo

```{r}
sessionInfo()
```

### PRG

```{r}
set.seed(43)
```

### Paths

```{r}
BASEPATH <- pathlibr::Path$new(".")
stopifnot("prepare.Rmd" %in% names(BASEPATH$dir))
```

```{r}
path_to <- (function(.) Sys.glob(BASEPATH$join("../..")$join(.)$show))
```

```{r}
out_file <- (function(.) BASEPATH$join("output")$join(.)$show)
dir.create(out_file(""), showWarnings = FALSE)
```

### Dataframes

```{r}
# Use first column as index
by_col1 <- (function(.) tibble::column_to_rownames(., colnames(.)[1]))
# Use index as new column `name`
ind2col <- (function(., name) tibble::rownames_to_column(., var = name))
```

```{r}
Sys.setenv("VROOM_CONNECTION_SIZE" = 131072 * 4)
from_csv <- function(.) {
  vroom::vroom(., del = "\t", progress = FALSE) %>%
    by_col1() %>%
    suppressMessages()
}
```

```{r}
# Precede by `ind2col("name for index")` to write the row names
to_csv <- function(., f) {
  vroom::vroom_write(., out_file(f), delim = "\t")
}
```

```{r}
# Constructs a `SingleCellExperiment` checking consistency of sample names
make_sce <- function(counts, coldata) {
  # Check that samples in counts = genes x samples
  # are ordered as in coldata = samples x metafields
  stopifnot(assertthat::are_equal(colnames(counts), rownames(coldata)))
  SingleCellExperiment::SingleCellExperiment(
    assays = list(counts = counts), colData = coldata
  )
}
```

```{r}
rbindlist <- function(L) { do.call("rbind", L) }
```

### TaxID

```{r}
taxid <- list(mm = 10090, hs = 9606)
```


## OmnipathR

### TF

Load the transcription factor data.

```{r}
omnipath.tf <-
  taxid %>%
  lapply(function(organism) {
    OmnipathR::import_dorothea_interactions(
      resources = c("DoRothEA"),
      dorothea_levels = c('A', 'B', 'C', 'D'),  # 'E' not available
      organism = organism
    ) %>%
      mutate(organism = organism)
  }) %>%
  rbindlist()
```

Examples of transcription factors:

```{r}
omnipath.tf %>%
  pull(source_genesymbol) %>%
  unique() %>%
  sort() %>%
  sample(5)
```

Write dataframe to file.

```{r}
omnipath.tf %>%
  ind2col("id") %>%
  readr::write_tsv(out_file("omnipath_tf.csv.gz"))
```

Read example:

```{r}
out_file("omnipath_tf.csv.gz") %>%
  from_csv() %>%
  filter(organism == taxid$mm) %>% 
  pull(source_genesymbol) %>%
  unique() %>%
  sample(5)
```

## Interactions

```{r}
omnipath.in <- 
  taxid %>%
  lapply(function(organism) {
    OmnipathR::import_all_interactions(
      dorothea_levels = c('A', 'B'),
      organism = organism
    ) %>%
      mutate(organism = organism)
  }) %>%
  rbindlist()
```

Examples:

```{r}
omnipath.in %>%
  select(source_genesymbol, target_genesymbol, type) %>%
  head(5)
```

Contained types:

```{r}
omnipath.in %>% pull(type) %>% unique()
```

Save:

```{r}
omnipath.in %>%
  ind2col("id") %>%
  readr::write_tsv(out_file("omnipath_in.csv.gz"))
```

## Ligand-receptor

```{r}
omnipath.lr <- 
  taxid %>%
  lapply(function(organism) {
    OmnipathR::import_ligrecextra_interactions(
      organism = organism
    ) %>%
      mutate(organism = organism)
  }) %>%
  rbindlist()
```

Examples:

```{r}
omnipath.lr %>%
  select(source_genesymbol, target_genesymbol) %>%
  head(5)
```

Save:

```{r}
omnipath.lr %>%
  ind2col("id") %>%
  readr::write_tsv(out_file("omnipath_lr.csv.gz"))
```
