---
title: "kable inside a loop"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output: 
  html_document:
    toc: true
    toc_depth: 2
editor_options:
 chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(out.width = "100%")
```

```{r}
suppressPackageStartupMessages({requireNamespace("kableExtra"); library(dplyr);})
```

```{r}
kable <- function(.) { 
  (.) %>%
    kableExtra::kbl(., align = "c") %>%
    kableExtra::kable_paper("hover", full_width = FALSE)
}
```

```{r}
tables <- list(
  a = c(c(1:5), c(2:5), c(3:5)),
  b = c(c(1:6), c(2:6), c(3:6)),
  b = c(c(1:7), c(2:7), c(3:7)),
  b = c(c(1:9), c(2:9), c(3:9))
)
```

```{r}
prepare <- function(.) {
  (.) %>%
    table() %>%
    as.data.frame() %>%
    t() 
}
```

Expected results like this:

```{r}
tables$a %>% prepare() %>% kable()
```

This works:

```{r, results='asis'}
for (t in tables) {
  t %>% prepare() %>% kable() %>% print()
}
```

But this?


## Section {.tabset .tabset-fade .tabset-pills}

### 1 {.tabset .tabset-fade}

#### Test 2

```{r, cache=TRUE}
1234
```

```{r}
kable_all <- function(tt) {
  for (t in tt) {
    t %>% prepare() %>% kable() %>% print()
  }
}
```

```{r, results='asis'}
tables %>% kable_all()
```
