---
title: "plotly scatter3d"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output: 
  html_document:
    toc: true
    toc_depth: 2
editor_options:
 chunk_output_type: console
---


```{r setup, include=FALSE}
# https://bookdown.org/yihui/rmarkdown-cookbook/fold-show.html

knitr::opts_knit$set(root.dir = '.')
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(out.width = "100%")
knitr::opts_chunk$set(fig.width = 10, fig.height = 8)

# https://stackoverflow.com/questions/63595786/rmarkdown-how-to-embed-an-3d-plot
#options(rgl.useNULL = TRUE) # Suppress the separate window.
```

```{r}
suppressPackageStartupMessages({
  library(ggplot2)
  library(dplyr)
  
  requireNamespace("plotly")
})
```


## Preliminaries {.tabset .tabset-fade}

### Introduction

```{r}
plotter <- function(df) {
  df %>%
    with({
      plotly::plot_ly() %>%
      plotly::add_markers(
        x = x, y = y, z = z,
        color = group
      )
    })
}
```

## Pre-Test {.tabset .tabset-fade}

```{r, fig.height=3}
randu %>%
  ggplot(aes(x = x, y = y)) + geom_point()
```


## Test 2 {.tabset .tabset-fade}

```{r, message=FALSE, dpi=72}
randu %>%
  mutate(group = (1:nrow(.)) %% 3) %>%
  plotter()
```


## Test 3 {.tabset .tabset-fade}

```{r, cache=TRUE, message=FALSE, dpi=72}
randu %>%
  mutate(group = (1:nrow(.)) %% 3) %>%
  plotter()
```

