---
title: "Figures that slide"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output: 
  html_document
editor_options:
 chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(out.width = "40%", dpi = 36)
```

```{js, echo=FALSE}
$(".main-container").css({'min-height': '2048px'})
```

```{js, out.extra='class="scrollable_js"'}
$(document).ready(
  function() {
    $("img.zoomable").on("click", function(evt) {
      if (!evt.originalEvent.shiftKey && evt.originalEvent.altKey) {
        var el = $(this).clone();
        el.attr("width", "2048px");
        window.open().document.write(el.wrap('<p>').parent().html());
        return false;
      }
    });
  }
);

$(document).ready(
  function() {
    $("img.scrollable").css({
      'position': 'absolute', 'top': 0, 'left': 0, 'z-index': 100000,
    });
    
    var parent = $("img.scrollable").parent();
    
    parent.css({'position': 'relative'});
    parent.find('img:first').css({'position': 'relative'});
    
    // associate a 'history' stack with each parent
    parent.each(function(i, el) { $(el).data("stack", new Array()); })
    
    $("img.scrollable").on("click", function(evt) {
      if (evt.originalEvent.altKey) return true;
      
      if (!evt.originalEvent.shiftKey) {
        var last = $(this);
        last.parent().data("stack").push(last);
        if (last) last.css({'z-index': parseInt(last.css('z-index'), 10) - 1});
      } else {
        var last = $(this).parent().data("stack").pop();
        if (last) last.css({'z-index': parseInt(last.css('z-index'), 10) + 1});
      }
      
      evt.stopPropagation();
      return false;
    });
  }
);
```


```{r}
suppressPackageStartupMessages({
  library(ggplot2)
  library(dplyr)
})
```

```{r}
figures <- function() {
  list(
    x = randu %>% ggplot(aes(x = x, y = y)) + geom_point() + ggtitle("Zoomable 1"),
    y = randu %>% ggplot(aes(x = x, y = z)) + geom_point() + ggtitle("Zoomable 2"),
    z = randu %>% ggplot(aes(x = y, y = z)) + geom_point() + ggtitle("Zoomable 3")
  )
}
```

```{r, out.extra='id="myfig" class="scrollable zoomable"', results='hide'}
figures()
```

```{r}
# Intermediate 1
```


```{r, out.extra='id="myfig" class="scrollable"', results='hide'}
figures()
```

```{r}
# Intermediate 2
```

```{r, out.extra='id="myfig" class="scrollable"', results='hide'}
requireNamespace("pheatmap")
list(A = 1:5, B = 1:9) %>%
  lapply(function(ii) {
    pheatmap::pheatmap(randu[ii, ], cluster_rows = F, cluster_cols = F) %>%
      magrittr::use_series(gtable)
  })
```

## 

```{html}
hello
```
