---
title: "ggplot manual color"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output: 
  html_document
editor_options:
 chunk_output_type: console
---


```{r}
suppressPackageStartupMessages({
  library(ggplot2)
  library(dplyr)
})

color_map <- list(r = "red", g = "green", b = "blue")

randu %>%
  mutate(color_key = as.factor(if_else(x > y, "r", "g"))) %>%
  ggplot(aes(x = x, y = y, fill = color_key)) + 
  scale_fill_manual(values = color_map) +
  geom_point(shape = 21, size = 7)
```

```{r}
randu %>%
  mutate(color_key = as.factor(if_else(x > y, "r", "g"))) %>%
  {
    ggplot(., aes(x = x, y = y, fill = color_key)) + 
      # scale_fill_manual(values = color_map, breaks = .$col) +
      scale_fill_manual(values = color_map[.$col]) +  # Alternative
      geom_point(shape = 21, size = 7)
  }
```

```{r}
randu %>%
  mutate(color_key = as.factor(if_else(x > y, "r", "g"))) %>%
  {
    ggplot(., aes(x = x, y = y, fill = color_key)) + 
      scale_fill_manual(values = color_map, limits = force) +
      geom_point(shape = 21, size = 7)
  }
```


```{r}
gglast <- function(what) {
  p <- ggplot2::last_plot()
  q <- p$mapping[[deparse(substitute(what))]]
  #print(p$data)
  #print(p$mapping)
  rlang::eval_tidy(q, data = p$data)
}

randu %>%
  mutate(color_key = as.factor(if_else(x > y, "r", "g"))) %>%
  ggplot(aes(x = x, y = y, fill = color_key)) + 
  scale_fill_manual(values = color_map, breaks = gglast(fill)) +
  geom_point(shape = 21, size = 7)
```

